---
- hosts: localhost
  connection: local
  become: true
  vars:
    - pdns_download_url: 'https://downloads.powerdns.com/releases/deb'
    - pdns_recursor_version: '3.7.3-1'
  tasks:
    - name: Installing ca-certificates
      apt:
        name: "ca-certificates"
        state: "latest"

    - name: Installing dumb-init
      apt:
        deb: "https://github.com/Yelp/dumb-init/releases/download/v1.0.2/dumb-init_1.0.2_amd64.deb"

    - name: Installing Powerdns Pre-Reqs
      apt:
        name: "{{ item }}"
        state: "present"
        force: "yes"
        install_recommends: no
      with_items:
        - 'dnsutils'

    - name: Installing Powerdns Recursor
      apt:
        deb: "{{ pdns_download_url }}/pdns-recursor_{{ pdns_recursor_version }}_amd64.deb"
        state: "present"
        install_recommends: no
