---
- hosts: localhost
  become: true
  connection: local
  vars:
    - pdns_download_url: 'https://downloads.powerdns.com/releases/deb'
    - pdns_recursor_version: '3.7.3-1'
  tasks:
    - name: Installing ca-certificates
      apt:
        name: "ca-certificates"
        state: "latest"

    - name: Installing Powerdns Recursor
      apt:
        deb: "{{ pdns_download_url }}/pdns-recursor_{{ pdns_recursor_version }}_amd64.deb"
        state: "present"
        install_recommends: no
